- name: start consul client
  shell: |
    CONSUL_UI_BETA=true \
    nohup consul agent \
    -bind="{{ ansible_eth1.ipv4.address }}" \
    -client="{{ ansible_eth1.ipv4.address }}" \
    -config-dir="{{ CONSUL_CONF_DIR }}" \
    -data-dir="{{ CONSUL_DATA_DIR }}" \
    -disable_anonymous_signature=true \
    -disable_update_check=true \
    -enable-script-checks=true \
    -join=192.168.77.21 \
    -node=agent-"agent-{{ inventory_hostname }}" \
    -ui \
    >> /tmp/consul.log 2>&1 &
